name: Post to Mastodon

on:
  push:
    branches:
      - main

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Mastodon
        uses: cbrgm/mastodon-github-action@v1
        with:
          access-token: ${{ secrets.MASTODON_TOKEN }}
          instance: "https://datasci.social"   # your Mastodon server
          status: "New update on my GitHub repo: ${{ github.repository }} — ${{ github.event.head_commit.message }}"

